### ISSUE TITLE
download-models.sh targets wrong shell

### ISSUE THREAD

**Issue by stephenreay** [westei/stanbol-stanfordnlp#13]
The script `models/download-models.sh` uses `set -o pipefail` but has a shebang line targeting `/bin/sh`

On Debian/similar systems, `/bin/sh` is provided by Dash, not Bash, and the Bash `pipefail` option is not supported.

You should either use POSIX/Bourne shell supported options, or change the shebang to use Bash explicitly.

**Comment by afduarte** [comment]
Just bumping this issue. Changing the shebang to use bash solved the problem for me, it's an easy fix and seems to work for everyone.
