### ISSUE TITLE
stanbol-stanfordnlp-masterX/core/src/main/java/at/salzburgresearch/stanbol/enhancer/nlp/stanford/mappings/TagSetRegistry.java:[398,62] error: cannot access IRI

### ISSUE THREAD

**Issue by molhaMaleh** [westei/stanbol-stanfordnlp#16]
while building the international server and after executing this command in the model directory
`download-install.sh` 
and then executing this command also in the same directory
` mvn clean install -Dmaven-Dmaven.test.skip=true `
I got an error form maven telling that this repository in pom.xml is not exist 
    \<dependency\>
      \<groupId\>at.salzburgresearch.stanbol\</groupId\>
      \<artifactId\>stanbol-stanfordnlp-core\</artifactId\>
      \<version\>1.1.0-SNAPSHOT\</version\>
      \<scope\>test\</scope\>
    \</dependency\>
so i deleted it from pom and after that build succeeded but when executing 
` mvn clean install -Dmaven-Dmaven.test.skip=true `
in the root directory (stanbol-stanfordnlp-master) I got this error 
Compilation failure:
[ERROR] /home/X/Downloads/stanbol-stanfordnlp-masterX/core/src/main/java/at/salzburgresearch/stanbol/enhancer/nlp/stanford/mappings/TagSetRegistry.java:[398,62] error: cannot access IRI
[ERROR] 
[ERROR] class file for org.apache.clerezza.commons.rdf.IRI not found
[ERROR] /home/X/Downloads/stanbol-stanfordnlp-masterX/core/src/main/java/at/salzburgresearch/stanbol/enhancer/nlp/stanford/mappings/TagSetRegistry.java:[403,23] error: no suitable constructor found for NerTag(String,UriRef)
[ERROR] 
[ERROR] constructor NerTag.NerTag(String,IRI) is not applicable
[ERROR] (actual argument UriRef cannot be converted to IRI by method invocation conversion)
[ERROR] constructor NerTag.NerTag(String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] /home/X/Downloads/stanbol-stanfordnlp-masterX/core/src/main/java/at/salzburgresearch/stanbol/enhancer/nlp/stanford/mappings/TagSetRegistry.java:[404,23] error: no suitable constructor found for NerTag(String,UriRef)
[ERROR] 
[ERROR] constructor NerTag.NerTag(String,IRI) is not applicable
[ERROR] (actual argument UriRef cannot be converted to IRI by method invocation conversion)
[ERROR] constructor NerTag.NerTag(String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] /home/X/Downloads/stanbol-stanfordnlp-masterX/core/src/main/java/at/salzburgresearch/stanbol/enhancer/nlp/stanford/mappings/TagSetRegistry.java:[405,23] error: no suitable constructor found for NerTag(String,UriRef)
[ERROR] 
[ERROR] constructor NerTag.NerTag(String,IRI) is not applicable
[ERROR] (actual argument UriRef cannot be converted to IRI by method invocation conversion)
[ERROR] constructor NerTag.NerTag(String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] /home/X/Downloads/stanbol-stanfordnlp-masterX/core/src/main/java/at/salzburgresearch/stanbol/enhancer/nlp/stanford/mappings/TagSetRegistry.java:[406,23] error: no suitable constructor found for NerTag(String,UriRef)

**Comment by abnud1** [comment]
adding version 0.12 to the dependencies org.apache.stanbol.enhancer.core and org.apache.stanbol.enhancer.nlp would fix this problem.  

The cause of this is probably incompatibility with the latest versions of these and since the latest versions might not be stable(yet) , depending on the stable versions is the wise solution here.

**Comment by westei** [comment]
HI

using the 0.12.0 version of the Stanbol dependencies is a good solution. The stanbol-trunk now uses a newer Apache Clerezza version that is not backward compatible. While the Stanbol code was adapted for the changed APIs of the new Clerezza version this project is not updated yet.

**Comment by molhaMaleh** [comment]
adding version tag 0.12.0 to Stanbol dependencies in all pom.xml files solved this problem.
really thankful for you @abnud1 , @westei
